apiVersion: v1
kind: Service
metadata:
  name: weather-api
  namespace: service-tracker
  labels:
    name: weather-api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3015
    targetPort: 3015
  selector:
    app: weather-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api
  namespace: service-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
        - image: msftgbb/weather-api:v1.0.10
          imagePullPolicy: Always
          name: weather-api
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          env:
            - name: DATA_SERVICE_URI
              value: http://data-api.service-tracker.svc.cluster.local:3009/     
          ports:
          - containerPort: 3015
            protocol: TCP
      restartPolicy: Always
