name: CI

on: [push, pull_request]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Kubernetes tools
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.16.2
          kustomize: 3.4.0
          helm: 2.16.1
          helmv3: 3.0.0
          command: |
            echo "Run kubeval"
            kubeval ./manifests/*.yaml --strict
